plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.boot:spring-boot-starter-restclient'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'
//	implementation("io.temporal:temporal-spring-boot-starter:1.36.1")

	implementation 'org.springframework.boot:spring-boot-starter-kafka'
	implementation(platform("io.namastack:namastack-outbox-bom:1.7.1"))
	implementation("io.namastack:namastack-outbox-starter-jdbc")
	implementation("io.namastack:namastack-outbox-kafka:1.7.2")
	implementation("io.namastack:namastack-outbox-jackson:1.7.1")
//	implementation 'org.springframework.boot:spring-boot-starter-batch'

	runtimeOnly("com.mysql:mysql-connector-j:9.7.0")

	runtimeOnly("com.skillsjars:jabrena__cursor-rules-java__301-frameworks-spring-boot-core:2026_04_23-9d8c173")


	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()
}
