spring.application.name: spring-aot-demo
management.endpoints.web.exposure.include: '*'
management.metrics.enable.jvm: true
logging:
   console:
      enabled: true
   level:
     org.apache.tika: DEBUG