spring.application.name: spring-aot-demo
management.endpoints.web.exposure.include: '*'
management.metrics.enable.jvm: true

logging:
   level:
      root: INFO
      com.example.demo: DEBUG
      # Enable Kafka logs for debugging
      org.springframework.kafka: warn
      org.apache.kafka: warn
      opentelemetry: off
      org.apache.kafka.streams: warn
spring:
   boot.admin.context-path: /admin
   datasource:
      url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8
      username: myuser
      password: mypassword
      driver-class-name: com.mysql.cj.jdbc.Driver
   kafka:
      bootstrap-servers: 127.0.0.1:9092
      listener:
         ack-mode: record
         concurrency: 3
         observation-enabled: true
      template:
         observation-enabled: true

      producer:
         value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
         properties:
           spring.json.add.type.headers: true

      consumer:
         # Resetting the consumer group to ensure we read from the beginning
         group-id: orders-1
         auto-offset-reset: earliest
         value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
         properties:
           spring.json.trusted.packages: "*"
           spring.json.use.type.headers: true
      admin:
         auto-create: true

      streams:
         application-id: order-stream-app
         properties:
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
bootui:
   path: /dev-console
   enabled: on
   transactions.enabled: on
   telemetry.enabled: on
management:
   opentelemetry:
      enabled: off
   endpoint:
      health:
         show-details: ALWAYS